use std::fmt::Write;

use crate::report;

const STYLE: &str = r#"
:root {
  --bg: #f6f7f9; --panel: #ffffff; --fg: #1b1f24; --muted: #5d6673; --border: #dde1e7;
  --accent: #2f6fde; --new: #1f8a4c; --changed: #c26a00; --same: #8a929c;
  --shadow: 0 1px 2px rgba(20, 24, 31, .06), 0 2px 8px rgba(20, 24, 31, .05);
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    --bg: #111418; --panel: #1a1e24; --fg: #e6e9ee; --muted: #9aa3ae; --border: #2c323a;
    --accent: #6ea0ff; --new: #4cc27f; --changed: #f0a040; --same: #7c848e;
    --shadow: 0 1px 2px rgba(0, 0, 0, .4);
  }
}
:root[data-theme="dark"] {
  --bg: #111418; --panel: #1a1e24; --fg: #e6e9ee; --muted: #9aa3ae; --border: #2c323a;
  --accent: #6ea0ff; --new: #4cc27f; --changed: #f0a040; --same: #7c848e;
  --shadow: 0 1px 2px rgba(0, 0, 0, .4);
}
* { box-sizing: border-box; }
body { margin: 0; background: var(--bg); color: var(--fg);
  font: 15px/1.5 system-ui, -apple-system, "Segoe UI", sans-serif; }
header.top { padding: 20px 16px 8px; max-width: 1400px; margin: 0 auto; }
h1 { font-size: 22px; margin: 0 0 4px; }
h2 { font-size: 18px; margin: 28px 0 8px; }
h3 { font-size: 15px; margin: 22px 0 10px; display: flex; gap: 10px; align-items: baseline; flex-wrap: wrap; }
h3 code { font-size: 14px; }
main { padding: 0 16px 60px; max-width: 1400px; margin: 0 auto; }
.meta { color: var(--muted); font-size: 13px; }
.summary { display: flex; gap: 8px; flex-wrap: wrap; margin: 10px 0 0; }
.chip { font-size: 12px; padding: 2px 9px; border-radius: 999px; border: 1px solid var(--border);
  background: var(--panel); color: var(--muted); text-decoration: none; }
a.chip:hover { color: var(--accent); border-color: var(--accent); }
.grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 14px; }
.card { background: var(--panel); border: 1px solid var(--border); border-radius: 10px;
  box-shadow: var(--shadow); overflow: hidden; display: flex; flex-direction: column; }
.card img { display: block; width: 100%; height: auto; border-bottom: 1px solid var(--border);
  background: var(--bg); }
.card .body { padding: 8px 10px 10px; display: flex; flex-direction: column; gap: 4px; min-width: 0; }
.row { display: flex; gap: 8px; align-items: center; justify-content: space-between; }
.id { font-weight: 600; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 13px; }
.status { font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: .04em; }
.status.new { color: var(--new); } .status.changed { color: var(--changed); }
.status.same, .status.first-run { color: var(--same); }
.path { font-size: 13px; overflow-wrap: anywhere; }
.loc { font-size: 12px; color: var(--muted); overflow-wrap: anywhere;
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }
details { font-size: 12px; color: var(--muted); }
details ul { margin: 4px 0 0; padding-left: 16px; }
.card:target { outline: 2px solid var(--accent); outline-offset: 2px; }
a { color: var(--accent); }
.notes li { color: var(--muted); font-size: 13px; }
"#;

pub fn index_html(
    manifest: &report::Manifest,
    previous: Option<&report::Manifest>,
    atlases: &[(String, String, String)],
) -> String {
    let mut html = String::new();
    let _ = write!(
        html,
        "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">\
         <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\
         <title>UI preview: {name}</title><style>{STYLE}</style></head><body>\
         <header class=\"top\"><h1>UI preview: {name}</h1>\
         <div class=\"meta\">driver <b>{driver}</b> &middot; {count} states &middot; \
         {edges} transitions &middot; generated by lele-ui-preview \
         (<a href=\"{changes}\">CHANGES.md</a>, <a href=\"{manifest_file}\">manifest.json</a>)</div>\
         <div class=\"summary\">{summary}</div></header><main>",
        name = escape(&manifest.crate_name),
        driver = escape(&manifest.driver),
        count = manifest.states.len(),
        edges = manifest.edges.len(),
        changes = report::CHANGES_FILE,
        manifest_file = report::MANIFEST_FILE,
        summary = summary_chips(manifest, previous, atlases),
    );
    let mut current_group = "";
    for (group, screen, atlas) in atlases {
        if group != current_group {
            let _ = write!(
                html,
                "<h2 id=\"{}\">{}</h2>",
                report::slug(group),
                escape(group)
            );
            current_group = group;
        }
        let states: Vec<&report::StateRecord> = manifest
            .states
            .iter()
            .filter(|s| &s.group == group && &s.screen == screen)
            .collect();
        let _ = write!(
            html,
            "<h3><code>{}</code><span class=\"meta\">{} states</span>\
             <a class=\"chip\" href=\"{}\">atlas</a></h3><div class=\"grid\">",
            escape(screen),
            states.len(),
            escape(atlas)
        );
        for state in states {
            html.push_str(&card(manifest, previous, state));
        }
        html.push_str("</div>");
    }
    if !manifest.notes.is_empty() {
        html.push_str("<h2>Notes</h2><ul class=\"notes\">");
        for note in &manifest.notes {
            let _ = write!(html, "<li>{}</li>", escape(note));
        }
        html.push_str("</ul>");
    }
    html.push_str("</main></body></html>\n");
    html
}

// needed helper: one state card with its screenshot, input path and outgoing transitions
fn card(
    manifest: &report::Manifest,
    previous: Option<&report::Manifest>,
    state: &report::StateRecord,
) -> String {
    let status = report::state_status(previous, state);
    let path = if state.path.is_empty() {
        "start".to_string()
    } else {
        state.path.join(" \u{203a} ")
    };
    let outgoing: Vec<&report::EdgeRecord> = manifest
        .edges
        .iter()
        .filter(|e| e.from == state.id)
        .collect();
    let mut edges = String::new();
    if !outgoing.is_empty() {
        let _ = write!(
            edges,
            "<details><summary>{} transitions</summary><ul>",
            outgoing.len()
        );
        for edge in outgoing {
            let _ = write!(
                edges,
                "<li>{} &rarr; <a href=\"#{}\">{}</a></li>",
                escape(&edge.action),
                escape(&edge.to),
                escape(&edge.to)
            );
        }
        edges.push_str("</ul></details>");
    }
    format!(
        "<article class=\"card\" id=\"{id}\"><a href=\"{png}\"><img loading=\"lazy\" src=\"{png}\" \
         alt=\"{id}\"></a><div class=\"body\"><div class=\"row\"><span class=\"id\">{id}</span>\
         <span class=\"status {status}\">{status}</span></div><div class=\"path\">{path}</div>\
         <div class=\"loc\">{loc}</div>{edges}</div></article>",
        id = escape(&state.id),
        png = escape(&state.png),
        path = escape(&path),
        loc = escape(&state.location),
    )
}

// needed helper: counts per status plus jump links per group
fn summary_chips(
    manifest: &report::Manifest,
    previous: Option<&report::Manifest>,
    atlases: &[(String, String, String)],
) -> String {
    let mut chips = String::new();
    for status in [report::STATUS_CHANGED, report::STATUS_NEW] {
        let count = manifest
            .states
            .iter()
            .filter(|s| report::state_status(previous, s) == status)
            .count();
        if count > 0 {
            let _ = write!(chips, "<span class=\"chip\">{count} {status}</span>");
        }
    }
    let mut groups: Vec<&str> = Vec::new();
    for (group, _, _) in atlases {
        if !groups.contains(&group.as_str()) {
            groups.push(group);
        }
    }
    for group in groups {
        let _ = write!(
            chips,
            "<a class=\"chip\" href=\"#{}\">{}</a>",
            report::slug(group),
            escape(group)
        );
    }
    chips
}

// needed helper: minimal HTML escaping for text and attribute values
fn escape(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

#[cfg(test)]
mod tests {
    use super::index_html;
    use crate::report;

    #[test]
    fn test_usage() {
        let manifest = report::Manifest {
            crate_name: "demo".to_string(),
            driver: "web".to_string(),
            states: vec![report::StateRecord {
                id: "s000".to_string(),
                group: "mobile".to_string(),
                screen: "/p/{id}".to_string(),
                path: vec!["open <menu>".to_string()],
                location: "/p/demo".to_string(),
                png: "mobile/p-id/s000.png".to_string(),
                fingerprint: "f".to_string(),
                pixel_hash: "p".to_string(),
            }],
            edges: vec![report::EdgeRecord {
                from: "s000".to_string(),
                to: "s000".to_string(),
                action: "press Escape".to_string(),
            }],
            notes: vec!["note".to_string()],
        };
        let atlases = vec![(
            "mobile".to_string(),
            "/p/{id}".to_string(),
            "mobile/p-id/atlas.png".to_string(),
        )];
        let html = index_html(&manifest, None, &atlases);
        assert!(html.contains("open &lt;menu&gt;"));
        assert!(html.contains("id=\"s000\""));
        assert!(html.contains("press Escape"));
        assert!(html.contains("first-run"));
    }
}
