[package]
name = "lele_bevy_lint"
version = "0.1.0"
edition = "2021"

[dependencies]
lele_lint = { path = "../lele_lint" }
clap = { version = "4", features = ["derive"] }
syn = { version = "2", features = ["full", "extra-traits", "visit"] }
proc-macro2 = { version = "1", features = ["span-locations"] }

[dev-dependencies]
tempfile = "3"
