[package]
name = "lele_lint"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "=4.6.6", features = ["derive"] }
walkdir = "=2.5.0"
thiserror = "=2.0.19"
serde = { version = "=1.0.229", features = ["derive"] }
toml = "=0.8.23"
syn = { version = "=2.0.119", features = ["full", "extra-traits", "visit"] }
proc-macro2 = { version = "=1.0.107", features = ["span-locations"] }
quote = "=1.0.47"
derive_more = { version = "=1.0.0", features = ["deref", "deref_mut"] }

[dev-dependencies]
tempfile = "=3.27.0"
