[package]
name = "lele_lint"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "=4.6.6", features = ["derive"] }
walkdir = "=2.5.0"
thiserror = "=2.0.19"
serde = { version = "=1.0.229", features = ["derive"] }
toml = "=0.8.23"
syn = { version = "=2.0.119", features = ["full", "extra-traits", "visit"] }
proc-macro2 = { version = "=1.0.107", features = ["span-locations"] }
quote = "=1.0.47"
derive_more = { version = "=1.0.0", features = ["deref", "deref_mut"] }

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"
case_sensitive_file_extension_comparisons = "allow"
explicit_iter_loop = "allow"
manual_let_else = "allow"
map_unwrap_or = "allow"
match_like_matches_macro = "allow"
match_same_arms = "allow"
match_wildcard_for_single_variants = "allow"
missing_const_for_fn = "allow"
missing_errors_doc = "allow"
must_use_candidate = "allow"
option_if_let_else = "allow"
or_fun_call = "allow"
ptr_arg = "allow"
redundant_clone = "allow"
redundant_closure_for_method_calls = "allow"
redundant_pub_crate = "allow"
semicolon_if_nothing_returned = "allow"
single_char_pattern = "allow"
too_many_lines = "allow"
uninlined_format_args = "allow"
unnecessary_trailing_comma = "allow"
unnested_or_patterns = "allow"
used_underscore_binding = "allow"
use_self = "allow"

[dev-dependencies]
tempfile = "=3.27.0"
