[package]
name = "cross_os_tests"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "=0.19.0"
bevy_app = "=0.19.0"
testing = { path = "../testing" }
tokio = { version = "=1.53.1", features = ["rt", "sync", "macros", "rt-multi-thread", "time"] }
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.151"
tracing = "=0.1.44"
tracing-subscriber = { version = "=0.3.23", features = ["env-filter"] }
