use crate::render_rule;
use std::fmt::Write;

use crate::Checker;

const CATEGORIES: [(&str, &str); 7] = [
    ("layout", "Layout: files and folders"),
    ("delegates", "Delegates: methods and `methods/`"),
    ("imports", "Imports and re-exports"),
    ("types", "Types"),
    ("tests", "Tests"),
    ("style", "Style"),
    ("config", "Crate config"),
];

const HEADER: &str = "# lele_lint rules

Generated by `lele_lint --rules-md`; do not edit by hand. Regenerate with
`LELE_BLESS=1 cargo nextest run --test rules_md` (the test fails while this file is stale).

Every rule is always on and always an error. `lele_lint --explain <CODE>` prints one rule.

Each example is a whole crate. Files not shown get these defaults: an empty `src/lib.rs`,
and a `Cargo.toml`, `clippy.toml` and `lele.toml` that already satisfy E021 and E022.
Every **Bad** example reports its rule's code (it may report others too);
every **Good** example reports nothing at all.

";

pub fn rules_markdown(checkers: &[Box<dyn Checker>]) -> String {
    let mut out = String::from(HEADER);
    for (category, title) in CATEGORIES {
        let mut in_category: Vec<&Box<dyn Checker>> = checkers
            .iter()
            .filter(|c| c.doc().category == category)
            .collect();
        if in_category.is_empty() {
            continue;
        }
        in_category.sort_by_key(|c| c.code());
        let _ = writeln!(out, "## {title}\n");
        for checker in &in_category {
            let _ = writeln!(
                out,
                "- [{} `{}`](#{}-{}): {}",
                checker.code(),
                checker.name(),
                checker.code().to_lowercase(),
                checker.name(),
                checker.doc().summary
            );
        }
        out.push('\n');
        for checker in in_category {
            out.push_str(&render_rule(checker.as_ref()));
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::rules_markdown;
    use crate::checkers::build_checkers;

    #[test]
    fn test_usage() {
        let checkers = build_checkers();
        let text = rules_markdown(&checkers);
        assert!(text.starts_with("# lele_lint rules"));
        for checker in &checkers {
            assert!(text.contains(&format!("### {} `{}`", checker.code(), checker.name())));
        }
    }
}
