pub(crate) mod atomic_delegates;
mod atomic_delegates_check;
pub(crate) mod atomic_file;
mod atomic_file_check;
mod build_checkers;
pub(crate) mod clippy_config_cargo;
mod clippy_config_cargo_check;
pub(crate) mod clippy_config_clippy;
mod clippy_config_clippy_check;
pub(crate) mod constants_placement;
mod constants_placement_check;
pub(crate) mod constructor_no_skip;
mod constructor_no_skip_check;
pub(crate) mod container_placement;
mod container_placement_check;
pub(crate) mod delegate_macro;
mod delegate_macro_check;
pub(crate) mod domain_import;
mod domain_import_check;
pub(crate) mod helper_count;
mod helper_count_check;
pub(crate) mod method_file_co_location;
mod method_file_co_location_check;
pub(crate) mod method_visibility;
mod method_visibility_check;
pub(crate) mod methods_layout;
mod methods_layout_check;
pub(crate) mod mod_rs_purity;
mod mod_rs_purity_check;
pub(crate) mod no_allow_attributes;
mod no_allow_attributes_check;
pub(crate) mod no_collection_newtype;
mod no_collection_newtype_check;
pub(crate) mod no_comments;
mod no_comments_check;
pub(crate) mod no_crate_paths;
mod no_crate_paths_check;
pub(crate) mod no_cross_domain_reexport;
mod no_cross_domain_reexport_check;
pub(crate) mod no_dunder_tests;
mod no_dunder_tests_check;
pub(crate) mod no_positional;
mod no_positional_check;
pub(crate) mod no_stuttered_path;
mod no_stuttered_path_check;
pub(crate) mod no_stuttered_type;
mod no_stuttered_type_check;
pub(crate) mod no_super_imports;
mod no_super_imports_check;
pub(crate) mod no_trivial_accessors;
mod no_trivial_accessors_check;
pub(crate) mod root_reexport;
mod root_reexport_check;
pub(crate) mod single_caller_type;
mod single_caller_type_check;
pub(crate) mod single_field_newtype;
mod single_field_newtype_check;
pub(crate) mod snake_case_files;
mod snake_case_files_check;
pub(crate) mod test_inline;
mod test_inline_check;
pub(crate) mod test_usage;
mod test_usage_check;

pub use build_checkers::build_checkers;
