use std::path::Path;
use std::path::PathBuf;

use serde_json::Value;

use crate::Error;
use crate::Report;

/// # Errors
/// Returns [`Error`] when `root` is not a git checkout, a crate hook file is
/// missing or unusable, or the combined file or hook pointer cannot be written.
pub fn resync(root: &Path) -> Result<Report, Error> {
    let absolute = root.canonicalize().map_err(|err| Error::Unusable {
        path: root.to_string_lossy().to_string(),
        message: err.to_string(),
    })?;
    let root = absolute.as_path();
    if !root.join(".git").exists() {
        return Err(Error::NoGit(root.to_string_lossy().to_string()));
    }
    let mut hooks = Vec::new();
    let mut per_crate = Vec::new();
    for crate_dir in crate_dirs(root) {
        let (name, crate_hooks) = read_crate_hooks(&crate_dir)?;
        let count = crate_hooks.len();
        hooks.extend(prefix_hook_ids(&name, crate_hooks, &crate_dir)?);
        per_crate.push((name, count));
    }
    hooks.push(root_hook());
    let config_path = root.join(".pre-commit-config.yaml");
    std::fs::write(&config_path, combined_document(&hooks)?).map_err(|err| Error::Unusable {
        path: config_path.to_string_lossy().to_string(),
        message: err.to_string(),
    })?;
    let pointer_updated = restore_pointer(root, &config_path.to_string_lossy())?;
    Ok(Report {
        hooks_per_crate: per_crate,
        config_path: config_path.to_string_lossy().to_string(),
        pointer_updated,
    })
}

fn crate_dirs(root: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let Ok(entries) = std::fs::read_dir(root) else {
        return out;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() && path.join("devenv.nix").exists() {
            out.push(path);
        }
    }
    out.sort();
    out
}

fn read_crate_hooks(crate_dir: &Path) -> Result<(String, Vec<Value>), Error> {
    let name = crate_dir.file_name().map_or_else(
        || "unknown".to_owned(),
        |file_name| file_name.to_string_lossy().to_string(),
    );
    let yaml = crate_dir.join(".pre-commit-config.yaml");
    if !yaml.exists() {
        return Err(Error::YamlMissing(name));
    }
    let unusable = |message: String| Error::Unusable {
        path: yaml.to_string_lossy().to_string(),
        message,
    };
    let text = std::fs::read_to_string(&yaml).map_err(|err| unusable(err.to_string()))?;
    let body: String = text
        .lines()
        .filter(|line| !line.trim_start().starts_with('#'))
        .collect::<Vec<&str>>()
        .join("\n");
    let parsed: Value = serde_json::from_str(&body).map_err(|err| unusable(err.to_string()))?;
    let hooks = parsed
        .get("repos")
        .and_then(Value::as_array)
        .and_then(|repos| repos.first())
        .and_then(|repo| repo.get("hooks"))
        .and_then(Value::as_array)
        .cloned()
        .ok_or_else(|| unusable("no repos[0].hooks array".to_owned()))?;
    Ok((name, hooks))
}

// needed helper: prek requires unique hook ids in one config file
fn prefix_hook_ids(name: &str, hooks: Vec<Value>, crate_dir: &Path) -> Result<Vec<Value>, Error> {
    let mut out = Vec::with_capacity(hooks.len());
    for mut hook in hooks {
        let id = hook
            .get("id")
            .and_then(Value::as_str)
            .ok_or_else(|| Error::Unusable {
                path: crate_dir.to_string_lossy().to_string(),
                message: "hook entry has no string id".to_owned(),
            })?
            .to_owned();
        let obj = hook.as_object_mut().ok_or_else(|| Error::Unusable {
            path: crate_dir.to_string_lossy().to_string(),
            message: "hook entry is not an object".to_owned(),
        })?;
        let _ = obj.insert("id".to_owned(), Value::String(format!("{name}-{id}")));
        out.push(hook);
    }
    Ok(out)
}

// needed helper: the root hook has no crate directory; root devenv.nix owns it
fn root_hook() -> Value {
    serde_json::json!({
        "id": "lele-enforce-config",
        "name": "lele_enforce_config (root)",
        "entry": "bash -c 'devenv tasks run lele:enforce-config 2>&1'",
        "language": "system",
        "always_run": true,
        "pass_filenames": false
    })
}

// needed helper: JSON text is valid YAML and matches the generated files byte-for-byte in style
fn combined_document(hooks: &[Value]) -> Result<String, Error> {
    let document = serde_json::json!({
        "default_stages": ["pre-commit"],
        "repos": [{"repo": "local", "hooks": hooks.to_owned()}]
    });
    let pretty = serde_json::to_string_pretty(&document).map_err(|err| Error::Unusable {
        path: "combined document".to_owned(),
        message: err.to_string(),
    })?;
    let mut text =
        "# Generated by `devenv tasks run hooks:resync` — do not hand-edit.\n".to_owned();
    text.push_str(&pretty);
    text.push('\n');
    Ok(text)
}

// needed helper: rewrites only the --config path, preserving prek's own store path
fn restore_pointer(root: &Path, config: &str) -> Result<bool, Error> {
    let hook = root.join(".git/hooks/pre-commit");
    let hook_display = hook.display().to_string();
    let text =
        std::fs::read_to_string(&hook).map_err(|_| Error::HookMissing(hook_display.clone()))?;
    let Some(line) = text.lines().find(|line| line.contains("--config=")) else {
        return Err(Error::HookMissing(hook_display));
    };
    let Some((head, rest)) = line.split_once("--config=\"") else {
        return Err(Error::HookMissing(hook_display));
    };
    let Some((_, tail)) = rest.split_once('"') else {
        return Err(Error::HookMissing(hook_display));
    };
    let updated = format!("{head}--config=\"{config}\"{tail}");
    if updated == line {
        return Ok(false);
    }
    let new_text = text.replacen(line, &updated, 1);
    std::fs::write(&hook, new_text).map_err(|err| Error::Unusable {
        path: hook_display,
        message: err.to_string(),
    })?;
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::resync;
    use crate::Error;

    // needed helper: builds a fixture crate with a generated-style hook yaml
    fn write_crate(root: &std::path::Path, name: &str, ids: &[&str]) {
        let dir = root.join(name);
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("devenv.nix"), "git-hooks.hooks = {};\n").unwrap();
        let hooks: Vec<String> = ids
            .iter()
            .map(|id| {
                format!(
                    "{{\"id\": \"{id}\", \"name\": \"{id} ({name})\", \"entry\": \"bash -c 'cd {name} && devenv tasks run lele:clippy 2>&1'\", \"language\": \"system\", \"always_run\": true, \"pass_filenames\": false}}"
                )
            })
            .collect();
        let yaml = format!(
            "# fixture comment\n{{\"default_stages\": [\"pre-commit\"], \"repos\": [{{\"repo\": \"local\", \"hooks\": [{}]}}]}}",
            hooks.join(", ")
        );
        std::fs::write(dir.join(".pre-commit-config.yaml"), yaml).unwrap();
    }

    // needed helper: parses the resync-written file back, skipping header comments
    fn hook_ids(combined: &str) -> Vec<String> {
        let body: Vec<&str> = combined
            .lines()
            .filter(|line| !line.starts_with('#'))
            .collect();
        let parsed: serde_json::Value = serde_json::from_str(&body.join("\n")).unwrap();
        parsed
            .get("repos")
            .and_then(serde_json::Value::as_array)
            .and_then(|repos| repos.first())
            .and_then(|repo| repo.get("hooks"))
            .and_then(serde_json::Value::as_array)
            .unwrap()
            .iter()
            .map(|hook| {
                hook.get("id")
                    .and_then(serde_json::Value::as_str)
                    .unwrap()
                    .to_owned()
            })
            .collect()
    }

    #[test]
    fn test_usage() {
        let dir = tempfile::tempdir().unwrap();
        write_crate(dir.path(), "aaa", &["lele-clippy", "lele-fmt"]);
        write_crate(dir.path(), "bbb", &["lele-clippy"]);
        std::fs::create_dir_all(dir.path().join(".git/hooks")).unwrap();
        std::fs::write(
            dir.path().join(".git/hooks/pre-commit"),
            "exec prek hook-impl --config=\"/stale/other.yaml\" -- \"$@\"\n",
        )
        .unwrap();
        let report = resync(dir.path()).unwrap();
        assert_eq!(
            report.hooks_per_crate,
            [("aaa".to_owned(), 2), ("bbb".to_owned(), 1),]
        );
        assert!(report.pointer_updated);
        let combined = std::fs::read_to_string(dir.path().join(".pre-commit-config.yaml")).unwrap();
        assert_eq!(
            hook_ids(&combined),
            vec![
                "aaa-lele-clippy".to_owned(),
                "aaa-lele-fmt".to_owned(),
                "bbb-lele-clippy".to_owned(),
                "lele-enforce-config".to_owned(),
            ]
        );
        let hook = std::fs::read_to_string(dir.path().join(".git/hooks/pre-commit")).unwrap();
        assert!(hook.contains(&report.config_path));
        let again = resync(dir.path()).unwrap();
        assert!(!again.pointer_updated);
    }

    #[test]
    fn test_missing_yaml_aborts() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(dir.path().join(".git")).unwrap();
        let krate = dir.path().join("lonely");
        std::fs::create_dir_all(&krate).unwrap();
        std::fs::write(krate.join("devenv.nix"), "git-hooks.hooks = {};\n").unwrap();
        let result = resync(dir.path());
        assert!(matches!(result, Err(Error::YamlMissing(_))));
    }

    #[test]
    fn test_no_git_skips() {
        let dir = tempfile::tempdir().unwrap();
        let result = resync(dir.path());
        assert!(matches!(result, Err(Error::NoGit(_))));
    }
}
