[package]
name = "testing"
version = "0.1.1"
edition = "2024"

[dependencies]
bevy = "0.19"
bevy_freenet = { path = ".." }
freenet = "0.2"
freenet-stdlib = { version = "0.8", features = ["net"] }
tokio = { version = "1", features = ["rt", "sync", "macros", "rt-multi-thread", "time", "net"] }
tempfile = "3"
bincode = "1"
hex = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
