[package]
name = "directory_contract"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[workspace]

[dependencies]
freenet-stdlib = { version = "=0.8.5", features = ["contract", "freenet-main-contract"] }
freenet-macros = "=0.2.0"
serde = { version = "=1.0.228", features = ["derive"] }
bincode = "=1.3.3"
blake3 = "=1.8.3"
thiserror = "=2.0.18"
