[workspace]

[package]
name = "roster_contract"
version = "0.1.1"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[features]
default = ["freenet-main-contract"]
freenet-main-contract = []

[dependencies]
freenet-stdlib = { version = "=0.8.5", features = ["contract"] }
freenet-macros = "=0.2.0"
serde = { version = "=1.0.229", features = ["derive"] }
bincode = "=1.3.3"

[profile.release]
lto = true
opt-level = "z"
strip = true
